### PR TITLE
Usability fixes for openconfig linter plugin

### PR DESCRIPTION
**Pull request by wenovus**
- Use symlink name instead of `os.path.realpath`, since some build
systems might use a temporary name for the file's canonical name.
- Output failed tests' stderr to user. Currently, they're all silenced,
and that makes debugging a pain.
- Update pyang dependency to latest version.
- Fix truncated commandline flag name causing naming conflict in new
pyang version (this is backwards-compatible).
- Make the fact that the repo is multi-license clear in the LICENSE file.

Updated repo to v0.1.10

### CODE REVIEW

**Review by robshakir — APPROVED** [review]
LGTM, thanks! Shall we push this to PyPI now?

**Comment by wenovus** [comment]
I want to wait a bit, I'm going to try my hand at making github actions work again.

**Comment by wenovus** [comment]
@robshakir Can you push to PyPI now? The .whl file in the repo is python2, and that's preventing `packaging.sh` from being able to run.

**Comment by robshakir** [comment]
Sorry - not sure I understand. The `.whl` file in which repo?

**Comment by wenovus** [comment]
Nevermind that comment, I realize now the `.whl` file is produced by `packaging.sh`.

**Pull request merged**
